version: '3.9'

networks:
  pieno-net:
    name: pieno-net

services:
  queue:
    image: redis:7.2.3
    networks:
      - pieno-net

  fuel-notifier: 
    image: emilianomaccaferri/pieno-fuel-notifier
    deploy:
      replicas: 3
      mode: dnsrr
    environment:
      - NOTIFICATION_GROUP=notification_listeners
      - BLOCK_TIME=60000 # how much should the consumer block for? 
      - STREAM_NAME=streams:notifications
      - REDIS_URL=redis://queue
      - ITEM_COUNT=10
      - DEAD_KEY_EXPIRY=100000 # how much time should pass before autoclaiming messages?
      - TELOXIDE_TOKEN=
      - TELEGRAM_CHAT_ID=-1002078353837 
    networks:
      - pieno-net
    
  fuel-meter:
    image: emilianomaccaferri/pieno-fuel-meter
    deploy:
      replicas: 3
    environment:
      - HTTP_PORT=3000
      - APP_NAME=fuel-meter-api
      - REDIS_URL=redis://queue
      - JWT_KEY=jwt_key_here
      - RUST_BACKTRACE=1
      - RUST_LOG=trace
      - REDIS_STREAM=streams:notifications
    networks:
      - pieno-net